# Generated by Django 5.0.7 on 2024-10-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPHapp', '0004_appointment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
